### ISSUE TITLE
Any chance of adding a SoundCloud integration?

### ISSUE THREAD

**Issue by itsbrex** [rigoneri/Syte2#5]
Not a programmer myself, otherwise I'd have a go at it. SoundCloud addition would be cool to display tracks listened to, hearted, or tracks uploaded/posted.

**Comment by rigoneri** [comment]
The first version of Syte had SoundCloud integration, but it was done by another developer, since I don't use SoundCloud. https://github.com/rigoneri/syte#soundcloud 

If I have some time I'll take a look at it.

**Comment by itsbrex** [comment]
Right on. Appreciate it. Sure is so cool btw. I'll send my sure when I get it up and running. :)
