### ISSUE TITLE
Wrong angular-animate version resolved

### ISSUE THREAD

**Issue by ngalaiko** [rigoneri/Syte2#7]
Hey! 
I've followed your instructions and run 'bower instal'l, but `angular-animate` and `angular` versions doesn't match at the end, so site wasn't working at all.
I was able to resolve this by editing `bower.json` like this:
```json

{
  "name": "client",
  "version": "0.0.0",
  "dependencies": {
    "angular": "1.4.0",
    "angular-animate": "1.4.0",
    "angular-route": "1.4.0",
    "angular-sanitize": "1.4.0",
    "moment": "2.13.0",
    "angular-moment": "0.10.3",
    "angular-modal-service": "0.10.1",
    "angular-lazy-img": "1.2.2",
    "google-maps": "3.2.1"
  },
  "devDependencies": {
    "angular-mocks": "1.4.0"
  },
  "appPath": "app",
  "moduleName": "clientApp",
  "resolutions": {
    "angular": "1.4.0",
    "moment": "2.13.0"
  }
}
```

Hope you can reproduce and  check it!

**Comment by ngalaiko** [comment]
have this at my pull request #8

**Comment by ghost** [comment]
I have just tried to run the project and @ngalayko is right.
I was having the mentioned error, it broke the build and when I applied his changes to my environment and ran bower install, everything was fixed.
Thanks !

Best Regards,
Eduardo Nicastro
